### ISSUE TITLE
Gingeh wallpaper link not working

### ISSUE THREAD

**Issue by Rizen54** [avtzis/awesome-linux-ricing#1]
The link for https://github.com/Gingeh/wallpapers doesn't work since well Gingeh has no such repo related to wallpapers.

**Comment by avtzis** [comment]
thank you for noticing. we could replace gingeh's wallpaper repo with [zhichaoh's](https://github.com/zhichaoh/catppuccin-wallpapers), which looks very similar but with extra nice wallpapers
